# Joseph Kamara
## Week 12 04/05/22
### Python numpy creating, processing, transporting arrays

In [1]:
import numpy as np

In [8]:
arr_2d = np.array([[1,2,3,4,],[5,6,7,8]])
print (arr_2d)
print(arr_2d.ndim)
print (arr_2d.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [9]:
#zero()
arr = np.zeros(10)

In [10]:
arr.ndim

1

In [11]:
arr_2d = np.zeros((5,5))

In [12]:
arr_2d.shape

(5, 5)

In [14]:
print(arr_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
arr_2d.ndim

2

In [16]:
#ones()
arr_2d = np.ones((6,6))

In [17]:
arr_2d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
arr_2d.shape

(6, 6)

In [19]:
arr_2d.ndim

2

In [24]:
arr_2d.dtype

dtype('float64')

In [28]:
#empty()
arr_2d = np.empty((2,2))

In [30]:
arr_2d = np.empty((3,3), dtype = int)

In [31]:
arr_2d

array([[16843009, 16843009, 16843009],
       [16843009, 16843009, 16843009],
       [16843009, 16843009, 16843009]])

In [32]:
#arrange 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
arr = np.arange(10,100,5)

In [36]:
print(arr)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [37]:
arr.ndim

1

In [38]:
arr.shape

(18,)

In [39]:
arr.dtype

dtype('int32')

In [41]:
arr = np.arange(1,13,1)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [42]:
#rehape an array
#1 D to 2-D
arr_2d = arr.reshape(3,4)

In [43]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr_2d.shape

(3, 4)

In [45]:
arr_2d = arr.reshape(6,2)

In [47]:
arr_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [52]:
#reshape 1 D to 3D 
arr
arr_3d = arr.reshape((2,2,3))

In [53]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr_3d.ndim

3

In [58]:
#reshape 3 to 2 
arr_3d = arr.reshape((3,2,2))

In [56]:
arr_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [59]:
arr_2d.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
# Unknown Dimension
arr_3d = arr.reshape(2,2,-1)

In [61]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr_3d = arr.reshape(2,-1,3)

In [63]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr_2d = np.array([[1,2,3,4,],[5,6,7,8,]])

In [66]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
arr_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
#iterating Array
arr = np.arange(10)

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
for n in arr: 
    print(n)

0
1
2
3
4
5
6
7
8
9


In [74]:
#iterating Array 2-D

for n in arr_2d: 
    print(n)

[1 2 3 4]
[5 6 7 8]


In [75]:
for n in arr_2d: 
    for x in n: 
        print(x)

1
2
3
4
5
6
7
8


In [80]:
#iterating 3-d array 

arr_3d = np.arange(12).reshape(2,2,3)

for n in arr_3d: 
    for x in n:
        print(x)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [81]:
for n in arr_3d: 
    for x in n:
        for y in x: 
            print(y)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [82]:
#nditer iterates on each scalar element in the np array 
for n in np.nditer(arr_3d):
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11


In [83]:
arr_2d = np.arange(12).reshape(3,4)

In [84]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
for n in np.nditer(arr_2d):
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11


In [96]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
arr_2d[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [101]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

0
2
4
6
8
10


In [103]:
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [104]:
for i,n in np.ndenumerate(arr):
    print(i,n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [105]:
arr_2d = np.arange(8).reshape(4,2)

In [106]:
arr_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [108]:
for i, n in np.ndenumerate(arr_2d):
    print(i,n)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7


In [110]:
#operations + , -, *, /
arr_2d* arr_2d

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49]])

In [111]:
arr_2d-arr_2d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [113]:
arr_2d + arr_2d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [114]:
arr_2d**2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49]], dtype=int32)

In [115]:
1 / arr_2d

c:\Miniconda\envs\py37_default\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        ],
       [0.5       , 0.33333333],
       [0.25      , 0.2       ],
       [0.16666667, 0.14285714]])

In [118]:
# Array indexing, slicing, specific rows and column 
arr = np.arange(1,13,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [120]:
arr[::3]

array([ 1,  4,  7, 10])

In [121]:
arr[0:6] = 100

In [122]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [124]:
arr_2d = np.array([[5,10,25],[15,10,20],[20,30,25]])

In [125]:
arr_2d.shape

(3, 3)

In [126]:
arr_2d[0]

array([ 5, 10, 25])

In [127]:
arr_2d[0,2]

25

In [133]:
arr_2d[:2]

array([[ 5, 10, 25],
       [15, 10, 20]])

In [134]:
arr_2d[:2][1:]

array([[15, 10, 20]])

In [135]:
arr_2d[:2]

array([[ 5, 10, 25],
       [15, 10, 20]])

In [136]:
arr_2d[:2,1:]

array([[10, 25],
       [10, 20]])

In [139]:
arr_2d[2,-1]

25

In [151]:
arr = np.zeros((9,9))

In [149]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [146]:
arr

array([[0., 0.],
       [0., 0.]])

In [147]:
print(arr)

[[0. 0.]
 [0. 0.]]
