# Joseph Kamara
## Week 12 04/07/22


In [1]:
import numpy as np

In [3]:
# Descriptive Statistics Measures
arr = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr.sum()

45

In [6]:
arr.sum(0)

array([12, 15, 18])

In [7]:
arr.sum(1)

array([ 6, 15, 24])

In [9]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np.sum(arr,axis =0)#this is getting the same results but with more steps 

array([12, 15, 18])

In [12]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [13]:
np.sum(arr,axis = None)

45

In [14]:
#mean
arr.mean()

5.0

In [15]:
arr.mean(1)

array([2., 5., 8.])

In [16]:
arr.mean(0)

array([4., 5., 6.])

In [17]:
np.mean(arr,axis = 0)

array([4., 5., 6.])

In [18]:
np.mean(arr, axis = 1)

array([2., 5., 8.])

In [20]:
#max 
arr.max()

9

In [21]:
arr.max(0)

array([7, 8, 9])

In [22]:
arr.max(1)

array([3, 6, 9])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.var()

6.666666666666667

In [25]:
arr.std()

2.581988897471611

In [26]:
arr = np.array([3,6,9,1,9,10,3,5,63,9,12,10,15,11,14])

In [27]:
arr.sort()

In [28]:
arr

array([ 1,  3,  3,  5,  6,  9,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [29]:
#Transpose 
arr= np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [30]:
t = arr.T

In [31]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [34]:
t.shape

(4, 2)

In [36]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [38]:
arr.transpose().shape

(4, 2)

In [40]:
print(arr.shape)

(2, 4)


In [41]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [43]:
arr.shape

(2, 4)

In [44]:
arr.transpose((0,1)).shape

(2, 4)

In [45]:
arr.transpose((1,0)).shape

(4, 2)

In [49]:
#transposing 3-D
arr_3D = np.arange(20).reshape((2,5,2))

In [51]:
print(arr_3D)
print(arr_3D.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [52]:
arr_3D.transpose((0,1,2))#no Change to the axis

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [53]:
arr_3D.transpose((0,1,2)).shape

(2, 5, 2)

In [54]:
arr_3D.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [55]:
arr_3D.transpose((1,0,2)).shape

(5, 2, 2)

In [57]:
#Random 
np.random.random((4,4))# between [0.0, 1.0] it never reaches 1 

array([[0.83196212, 0.04408609, 0.53253875, 0.81640212],
       [0.29964879, 0.34117842, 0.95073224, 0.53512233],
       [0.05447111, 0.78340892, 0.2410876 , 0.82323032],
       [0.63730482, 0.06232606, 0.88977542, 0.09880542]])

In [59]:
from numpy.random import random 
random((4,4))

array([[0.81129166, 0.04919959, 0.46910695, 0.28969868],
       [0.07993648, 0.52362366, 0.65739652, 0.91651147],
       [0.2611837 , 0.29651522, 0.61657729, 0.52536593],
       [0.42043275, 0.28458209, 0.25120893, 0.49966452]])

In [60]:
from numpy.random import randn 

In [63]:
randn(5,5)

array([[ 0.21473076,  0.23814157, -0.15673342,  0.25714384, -1.33529947],
       [-2.23559445,  1.28242354, -0.28968795,  0.9161233 ,  1.10269832],
       [-2.01473492, -0.8361257 , -0.08845001, -1.49900108,  1.63821932],
       [ 1.09287133,  0.56988297,  0.01886765, -0.84897282,  0.23664349],
       [ 0.81998773,  0.5467547 , -1.3168585 , -1.37848196, -1.09964687]])

In [65]:
np.random.randint(10,50)

22

In [67]:
#joining Numpy Arrays 
#1-d array 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [68]:
arr = np.concatenate((arr1, arr2))

In [69]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr.shape

(10,)

In [79]:
#2-D array 
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(arr1)
print ('\n array2')
print(arr2)

[[1 2]
 [3 4]]

 array2
[[5 6]
 [7 8]]


In [72]:
arr = np.concatenate((arr1,arr2))

In [73]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
arr1.shape


(2, 2)

In [81]:
arr2.shape

(2, 2)

In [83]:
arr.shape

(4, 2)

In [85]:
arr = np.concatenate((arr1,arr2), axis = 1)

In [86]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [88]:
arr.shape

(2, 4)

In [90]:
arr = np.concatenate((arr1,arr2), axis = 0)

In [91]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [92]:
#Splitting Numpy Arrays
arr = np.array([1,2,3,4,5,6])
arr_s = np.array_split(arr,3)

In [93]:
print(arr_s)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [95]:
arr_s[0]

array([1, 2])

In [96]:
arr_s[2]

array([5, 6])

In [102]:
website = "https://numpy.org/doc/stable/reference/ufuncs.html"

In [104]:
import webbrowser 
webbrowser.open(website)

True