# Joseph Kamara
## Week 11 - 03/31/2022
## Python Numpy- Processing Arrays 



In [1]:
import numpy as np  

In [3]:
lst  = [11,22,33,44,55,66,77]

In [4]:
arr = np.array(lst)

In [5]:
arr

array([11, 22, 33, 44, 55, 66, 77])

In [7]:
lst2 = [1.3,4.5,6.6]
arr2 = np.array(lst2)

In [8]:
arr2.dtype

dtype('float64')

In [9]:
fruits = ['Orange','Apple', 'Cherry','Grape']
my_str = np.array(fruits)

In [10]:
my_str

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [11]:
my_str.dtype

dtype('<U6')

In [12]:
d = ['Orange', 'Apple', 'Cherry', 'Grape',1,2,3,4,5, [6,7,8,9,10]]
arr_df = np.array(d)

In [13]:
arr_df

array(['Orange', 'Apple', 'Cherry', 'Grape', 1, 2, 3, 4, 5,
       list([6, 7, 8, 9, 10])], dtype=object)

In [15]:
arr_df.dtype

dtype('O')

In [16]:
my_arr2 = np.array([11,22,33,44,55], dtype = 'S')

In [17]:
my_arr2

array([b'11', b'22', b'33', b'44', b'55'], dtype='|S2')

In [18]:
print(my_arr2)

[b'11' b'22' b'33' b'44' b'55']


In [19]:
my_arr2.dtype

dtype('S2')

In [20]:
my_arr3 = np.array([1,2,3,4,5,6], dtype = 'i4')

In [21]:
my_arr3 

array([1, 2, 3, 4, 5, 6])

In [23]:
my_arr3.dtype

dtype('int32')

In [24]:
my_arr3 = np.array([1,2,3,4,5,6], dtype = 'i8')

In [25]:
my_arr3.dtype

dtype('int64')

In [26]:
#Converting Data Type on Existing Arrays 
# Using astype 
score = [99,9,98.7,89.5,78.9,100.0,88.99]

In [27]:
arr_scores = np.array(score)

In [29]:
arr_scores.dtype

dtype('float64')

In [30]:
arr_scores

array([ 99.  ,   9.  ,  98.7 ,  89.5 ,  78.9 , 100.  ,  88.99])

In [31]:
arr = arr_scores.astype('i')

In [32]:
arr

array([ 99,   9,  98,  89,  78, 100,  88], dtype=int32)

In [37]:
arr = np.array([1,0,0,1,4,5,6,9,1,0])

In [39]:
arr.dtype

dtype('int32')

In [40]:
arr_bool = arr.astype('bool')

In [41]:
arr_bool

array([ True, False, False,  True,  True,  True,  True,  True,  True,
       False])

In [42]:
print(arr)
print(arr_bool)

[1 0 0 1 4 5 6 9 1 0]
[ True False False  True  True  True  True  True  True False]


In [48]:
# NumPy Array Copy vs View 
# Creating an array from a nested list 
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]
my_list =[lst1,lst2]

In [49]:
my_list

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [50]:
print(my_list)

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]


In [51]:
arr = np.array(my_list)

In [52]:
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [53]:
arr.ndim


2

In [58]:
# copy and view, instead of using = 
c_arr = arr.copy()

In [59]:
c_arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [60]:
c_arr[0,0] = 10

In [61]:
c_arr

array([[10,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [66]:
c_arr[1,3] = 444

In [67]:
c_arr

array([[ 10,   2,   3,   4,   5],
       [ 11,  22,  33, 444,  55]])

In [68]:
arr_v = arr.view()

In [69]:
arr_v

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [72]:
arr_v[0,0] = 15

In [73]:
arr_v

array([[15,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [74]:
arr

array([[15,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [75]:
# NumPy Array Shape 
arr 

array([[15,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [76]:
arr.shape

(2, 5)

In [80]:
arr = np.array([1,2,3,4,5,6], ndmin = 5)

In [81]:
arr

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [83]:
arr.shape

(1, 1, 1, 1, 6)

In [84]:
a = np.array([[2,3,4,5],[6,7,8,9]])

In [85]:
print(np.shape(a))

(2, 4)


In [86]:
a.shape[0]

2

In [87]:
a.shape[1]

4

In [88]:
#several arrays can be stacked together and the shape is very importat 
# Stacking 
a = np.array([[1,2],
            [3,4]])
b = np.array([[5,6],
             [7,8]])

In [93]:
v= np.vstack((a,b))

In [94]:
v.shape

(4, 2)

In [96]:
#horazontal stack 
h = np.hstack((a,b))

In [98]:
h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [100]:
# Creating array from file 
    #This is where we are reading data from file / creating file 
    
f = open("data.txt","w")
f.write("1,2,3\n")
f.write("4,5,6")
f.close()

#reading from file 
f = open("data.txt","r")
print(f.read())
f.close()

1,2,3
4,5,6


In [103]:
# create np.array from file 
arr = np.genfromtxt("data.txt", dtype = None, encoding = None, delimiter = ",")
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arr.dtype

dtype('int32')

In [108]:
file_data = np.loadtxt("data1.txt", dtype =int)