# Joseph Kamara
## Week 11 - 03/29/2022
## Python Numpy Intro 



In [1]:
import numpy as np  

In [2]:
np.__version__

'1.18.5'

In [3]:
arr = np.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
print(arr)

[1 2 3 4 5 6]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr1 = np.array((1,2,3,4,5,6))

In [8]:
arr1

array([1, 2, 3, 4, 5, 6])

In [9]:
#Dimensions in Arrays: 
'''
0-D Arrays
'''
arr0 = np.array(50)

In [10]:
print(arr0)

50


In [11]:
arr0

array(50)

In [12]:
#1-D Array 
# an array that has 0-D-arrays as elements 
arr1 = np.array([0,1,2,3,45,6])

In [13]:
arr1

array([ 0,  1,  2,  3, 45,  6])

In [14]:
#2-D Array 
# an array that has 1-D-arrays as elements 
arr2 = np.array([[0,1,2,3,4,5,6],[4,5,6,7,8,9,10]])

In [15]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [16]:
#3-D Array 
# an array that has 2-D-arrays as elements 
arr3 = np.array([[[1,2,3,4],[4,5,6,7],[8,10,12,16]]])

In [17]:
arr3.ndim

3

In [18]:
print(arr3)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 8 10 12 16]]]


In [19]:
arr0.ndim

0

In [20]:
arr3.ndim

3

In [21]:
#create 4-D 
arr4 = np.array([1,2,3,4,5], ndmin = 4)

In [22]:
arr4

array([[[[1, 2, 3, 4, 5]]]])

In [23]:
#create 5-D 
arr5 = np.array([1,2,3,4,5], ndmin = 5)

In [24]:
arr5

array([[[[[1, 2, 3, 4, 5]]]]])

In [25]:
arr4.ndim

4

In [26]:
arr5.ndim

5

In [27]:
#Array indexing: how to access the data in the nimPi array 
arr1

array([ 0,  1,  2,  3, 45,  6])

In [28]:
arr1[2]

2

In [29]:
arr1[-1]

6

In [30]:
sum(arr1)

57

In [31]:
arr1[2] + arr1[-1]

8

In [32]:
#2-D array Access
arr2[0][1]

1

In [33]:
arr2.shape

(2, 7)

In [34]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [35]:
arr2[1][5]

9

In [36]:
arr3

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8, 10, 12, 16]]])

In [37]:
arr3.shape

(1, 3, 4)

In [38]:
arr3[0,-1]

array([ 8, 10, 12, 16])

In [39]:
#slicing np arrays
#1-d Array
arr1

'''
arr[start:]
'''

'\narr[start:]\n'

In [40]:
arr1[1:-3]

array([1, 2])

In [41]:
arr1[2:]

array([ 2,  3, 45,  6])

In [42]:
arr1[:5]

array([ 0,  1,  2,  3, 45])

In [43]:
print(arr1[-4:-1])

[ 2  3 45]


In [44]:
arr1[1:6:2]

array([1, 3, 6])

In [45]:
#Slicing 2-D Arrays 
arr2.shape
arr2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [46]:
arr2[0:2,1]

array([1, 5])

In [47]:
arr2[0:2,-1]

array([ 6, 10])

In [48]:
arr2[:,-1]

array([ 6, 10])

In [49]:
arr2[:,1:3]

array([[1, 2],
       [5, 6]])

In [50]:
arr2[1:,1:3]

array([[5, 6]])

In [51]:
#slicing 3-D array 
arr = np.array([[1,2,34],[1,3,4],[1,3,5]])

In [52]:
arr3.shape

(1, 3, 4)

In [53]:
arr3

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8, 10, 12, 16]]])

In [54]:
arr3[1:0:2,1,3]

array([], dtype=int32)

In [77]:
# Different data elements dim 
arr = np.array([ [ [1,2],[4,5],[[7,8],[[10,11,3]]] ] ])

In [78]:
arr.ndim

3

In [79]:
arr.shape

(1, 3, 2)

In [80]:
arr

array([[[1, 2],
        [4, 5],
        [list([7, 8]), list([[10, 11, 3]])]]], dtype=object)

In [81]:
arr[0]

array([[1, 2],
       [4, 5],
       [list([7, 8]), list([[10, 11, 3]])]], dtype=object)

In [82]:
arr[0,1][-1]

5

IndexError: index 1 is out of bounds for axis 0 with size 1